### ISSUE TITLE
Demo site is having issues

### ISSUE THREAD

**Issue by tomoguisuru** [mike-north/ember-perf#79]
visiting https://mike.works/ember-perf results in the following

```
UnrecognizedURLError: /ember-perf
   at Object.applyToState (/var/app/current/deploy-dist/fastboot/vendor-148a53dd64639e6f08701a4338f4eb1c.js:20:3035)
   at Object.T (/var/app/current/deploy-dist/fastboot/vendor-148a53dd64639e6f08701a4338f4eb1c.js:19:21466)
   at Object.transitionByIntent (/var/app/current/deploy-dist/fastboot/vendor-148a53dd64639e6f08701a4338f4eb1c.js:20:4155)
   at j (/var/app/current/deploy-dist/fastboot/vendor-148a53dd64639e6f08701a4338f4eb1c.js:19:24818)
   at Object.handleURL (/var/app/current/deploy-dist/fastboot/vendor-148a53dd64639e6f08701a4338f4eb1c.js:20:4506)
   at i._doURLTransition (/var/app/current/deploy-dist/fastboot/vendor-148a53dd64639e6f08701a4338f4eb1c.js:10:19729)
   at i.handleURL (/var/app/current/deploy-dist/fastboot/vendor-148a53dd64639e6f08701a4338f4eb1c.js:10:19645)
   at i.visit (/var/app/current/deploy-dist/fastboot/vendor-148a53dd64639e6f08701a4338f4eb1c.js:4:28690)
   at buildAppInstance.then.then.then (/var/app/current/node_modules/fastboot/src/ember-app.js:238:28)
   at k (/var/app/current/deploy-dist/fastboot/vendor-148a53dd64639e6f08701a4338f4eb1c.js:20:9049)
   at O (/var/app/current/deploy-dist/fastboot/vendor-148a53dd64639e6f08701a4338f4eb1c.js:20:9163)
   at E (/var/app/current/deploy-dist/fastboot/vendor-148a53dd64639e6f08701a4338f4eb1c.js:20:8952)
   at invokeWithOnError (/var/app/current/deploy-dist/fastboot/vendor-148a53dd64639e6f08701a4338f4eb1c.js:4:5816)
   at Object.flush (/var/app/current/deploy-dist/fastboot/vendor-148a53dd64639e6f08701a4338f4eb1c.js:4:6272)
   at Object.flush (/var/app/current/deploy-dist/fastboot/vendor-148a53dd64639e6f08701a4338f4eb1c.js:4:7042)
   at Object.end (/var/app/current/deploy-dist/fastboot/vendor-148a53dd64639e6f08701a4338f4eb1c.js:4:7387)
   at Timeout._onTimeout (/var/app/current/deploy-dist/fastboot/vendor-148a53dd64639e6f08701a4338f4eb1c.js:4:4613)
   at ontimeout (timers.js:365:14)
   at tryOnTimeout (timers.js:237:5)
   at Timer.listOnTimeout (timers.js:207:5)
```

**Comment by kiwiupover** [comment]
I will have a look into this tonight. Thanks for posting the issue

**Comment by mike-north** [comment]
Updated URL for test site: http://mike-north.github.io/ember-perf
